version: '3.7'

services:
  server:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: daphne server.asgi:application -b 0.0.0.0 -p 8000
    volumes:
      - static_volume:/home/app/server/staticfiles
    ports:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:latest
    volumes:
      - redis_data:/var/lib/redis/data/
    expose:
      - 6379

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/server/staticfiles
    ports:
      - 1338:80
    depends_on:
      - server

volumes:
  postgres_data:
  static_volume:
  redis_data: