version: '3.7'

services:

    client:
      build: ./client
      command: npm start
      container_name: client
      depends_on:
        - server
      ports:
        - 3000:3000
      stdin_open: true
      volumes:
        - ./client:/usr/src/app
      environment:
        - CHOKIDAR_USEPOLLING=true
        - REACT_APP_BASE_URL=http://localhost:8000

    server:
        build: ./server
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - ./server/:/usr/src/app/
        ports:
          - 8000:8000
        env_file:
          - ./.env.dev
        depends_on:
          - db

    db:
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=hello_django
          - POSTGRES_PASSWORD=hello_django
          - POSTGRES_DB=hello_django_dev

    redis:
      image: redis:latest
      volumes:
        - redis_data:/var/lib/redis/data/
      expose:
        - 6379

volumes:
  postgres_data:
  redis_data: